### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by SolarAquarion** [withoutboats/notty-encoding#5]
/home/solaraquarion/.cargo/git/checkouts/notty-encoding-f90d2d7580660013/master/src/lib.rs:1:1: 1:31 error: #[feature] may not be used on the stable release channel
/home/solaraquarion/.cargo/git/checkouts/notty-encoding-f90d2d7580660013/master/src/lib.rs:1 #![feature(associated_consts)]

**Comment by withoutboats** [comment]
As you may have realized already (in connection with your other PR) notty-encoding and notty only compile on nightly right now.
